#!/usr/bin/env python3
"""Generate replay_data.c from a psa_call trace captured with
CONFIG_SAMPLE_PSA_CALL_TRACE (see samples/crypto/psa_tls).

Usage: gen_replay.py <trace_full.log> <output.c>
"""
import re
import sys

ansi = re.compile(r"\x1b\[[0-9;]*m|\r")

calls = []
cur = None
for raw in open(sys.argv[1], errors="replace"):
    line = ansi.sub("", raw).strip()
    m = re.match(r"PSAC (\d+) h=(\w+) t=(-?\d+) il=(\d+) ol=(\d+)", line)
    if m:
        cur = {"seq": int(m.group(1)), "h": int(m.group(2), 16),
               "t": int(m.group(3)), "iv": [], "ov": [], "st": None}
        calls.append(cur)
        continue
    m = re.match(r"IV(\d+) @(\w+) l=(\d+) ?([0-9a-f]*)", line)
    if m and cur is not None:
        cur["iv"].append((int(m.group(2), 16), int(m.group(3)), m.group(4)))
        continue
    m = re.match(r"OV(\d+) @(\w+) l=(\d+)", line)
    if m and cur is not None:
        cur["ov"].append((int(m.group(2), 16), int(m.group(3))))
        continue
    m = re.match(r"RET (\d+) st=(-?\d+)", line)
    if m:
        seq = int(m.group(1))
        for c in reversed(calls):
            if c["seq"] == seq:
                c["st"] = int(m.group(2))
                break

# Drop incomplete trailing record (log cut mid-call is possible)
calls = [c for c in calls if c["st"] is not None]

out = open(sys.argv[2], "w")
out.write("/* Auto-generated by gen_replay.py - do not edit. */\n")
out.write('#include "replay.h"\n\n')

blob_parts = []
blob_off = 0
min_addr = 0xFFFFFFFF
max_addr = 0

records = []
for c in calls:
    ivs = []
    for addr, ln, hx in c["iv"]:
        data = bytes.fromhex(hx) if hx else b""
        ivs.append((addr, ln, blob_off, len(data)))
        blob_parts.append(data)
        blob_off += len(data)
        if ln:
            min_addr = min(min_addr, addr)
            max_addr = max(max_addr, addr + ln)
    ovs = []
    for addr, ln in c["ov"]:
        ovs.append((addr, ln))
        if ln:
            min_addr = min(min_addr, addr)
            max_addr = max(max_addr, addr + ln)
    records.append((c, ivs, ovs))

# Addresses below this collide with the replay application's own image
# RAM and are remapped to a shadow buffer at runtime.
REMAP_BELOW = 0x2F006000

low = [a for c, ivs, ovs in records for a, ln, *_ in ivs if a < REMAP_BELOW and ln]
low += [a for c, ivs, ovs in records for a, ln in ovs if a < REMAP_BELOW and ln]
low_lens = [ln for c, ivs, ovs in records for a, ln, *_ in ivs if a < REMAP_BELOW and ln]
low_lens += [ln for c, ivs, ovs in records for a, ln in ovs if a < REMAP_BELOW and ln]
if low:
    low_base = min(low)
    low_size = max(a + ln for a, ln in zip(low, low_lens)) - low_base
else:
    low_base = REMAP_BELOW
    low_size = 0
guard_addr = min([a for c, ivs, ovs in records for a, ln, *_ in ivs
                  if a >= REMAP_BELOW and ln] +
                 [a for c, ivs, ovs in records for a, ln in ovs
                  if a >= REMAP_BELOW and ln])

blob = b"".join(blob_parts)
out.write("const uint8_t replay_blob[%d] = {\n" % len(blob))
for i in range(0, len(blob), 16):
    out.write("\t" + ",".join("0x%02x" % b for b in blob[i:i + 16]) + ",\n")
out.write("};\n\n")

out.write("const struct replay_call replay_calls[%d] = {\n" % len(records))
for c, ivs, ovs in records:
    out.write("\t{ .seq = %d, .handle = 0x%x, .type = %d, .expected_st = %d,\n"
              % (c["seq"], c["h"], c["t"], c["st"]))
    out.write("\t  .n_in = %d, .n_out = %d,\n" % (len(ivs), len(ovs)))
    out.write("\t  .iv = {")
    for addr, ln, off, dlen in ivs:
        out.write(" {0x%x, %d, %d, %d}," % (addr, ln, off, dlen))
    out.write(" },\n\t  .ov = {")
    for addr, ln in ovs:
        out.write(" {0x%x, %d}," % (addr, ln))
    out.write(" } },\n")
out.write("};\n\n")
out.write("const uint32_t replay_num_calls = %d;\n" % len(records))
out.write("const uint32_t replay_min_addr = 0x%x;\n" % min_addr)
out.write("const uint32_t replay_max_addr = 0x%x;\n" % max_addr)
out.write("const uint32_t replay_remap_below = 0x%x;\n" % REMAP_BELOW)
out.write("const uint32_t replay_low_base = 0x%x;\n" % low_base)
out.write("const uint32_t replay_low_size = 0x%x;\n" % low_size)
out.write("const uint32_t replay_guard_addr = 0x%x;\n" % guard_addr)

print("calls=%d blob=%dB addr-range=0x%x..0x%x remap<0x%x: base=0x%x size=%d guard=0x%x"
      % (len(records), len(blob), min_addr, max_addr, REMAP_BELOW,
         low_base, low_size, guard_addr))
